# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = CDTT
DESTDIR = ../../x64/Debug
CONFIG += debug
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += GeneratedFiles
HEADERS += ./CDTTest.h \
    ./InputsModel.h \
    ./MainWindow.h
SOURCES += ./CDTTest.cpp \
    ./MainWindow.cpp \
    ./main.cpp
FORMS += ./MainWindow.ui
